<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/encoding_columntransform.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# In this dataset I have worked on Column transformer.
# There are few errors in this dataset but the process i worked with remains the same.
# In this dataset I have worked without column transform process and with column transform process.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df = pd.read_csv('/content/enhanced_fever_medicine_recommendation.csv', usecols = [2,3,1,18,17])
df.columns = ['Fever_Severity','Age','Gender','Blood_Pressure','Previous_Medication']
df= df[['Age','Gender','Fever_Severity','Blood_Pressure','Previous_Medication']]
df.head()

,Age,Gender,Fever_Severity,Blood_Pressure,Previous_Medication
0,89,Female,Normal,Normal,NaN
1,94,Male,Mild Fever,High,Ibuprofen
2,92,Male,Normal,High,NaN
3,66,Male,High Fever,High,Ibuprofen
4,28,Male,High Fever,Low,Paracetamol


In [ ]:
df['Blood_Pressure'].unique()

array(['Normal', 'High', 'Low'], dtype=object)

In [ ]:
df.isnull().sum()

,0
Age,0
Gender,0
Fever_Severity,0
Blood_Pressure,0
Previous_Medication,237


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('Previous_Medication',axis = 1), df['Previous_Medication'], test_size = 0.2)

In [ ]:
y_train

,Previous_Medication
647,Aspirin
802,Aspirin
625,Paracetamol
225,Ibuprofen
862,NaN
...,...
254,NaN
202,Aspirin
824,Paracetamol
931,Ibuprofen


In [ ]:
df['Previous_Medication'].unique()

array([nan, 'Ibuprofen', 'Paracetamol', 'Aspirin'], dtype=object)

In [ ]:
df['Previous_Medication'].value_counts()

,count
Previous_Medication,
Ibuprofen,259
Paracetamol,256
Aspirin,248


In [ ]:
#ode = fever,blood pressure oe= gender si=medicide but could be done if numerical

Without columns transform (long process)

In [ ]:
# for treating missing values of previous medication
si = SimpleImputer()
y_train_medication = si.fit_transform(y_train[['Previous_Medication']])
y_test_medication = si.fit_transform(y_test[['Previous_Medication']])

y_train_medication

KeyError: "None of [Index(['Previous_Medication'], dtype='object')] are in the [index]"

In [ ]:
# for oe for gender
oe = OrdinalEncoder(categories =[['Male','Female']])
x_train_gender = oe.fit_transform(x_train[['Gender']])
x_test_gender = oe.fit_transform(x_test[['Gender']])
x_train_gender

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],

In [ ]:
# ohe for fever and blood pressure
ohe = OneHotEncoder(drop = 'first',sparse_output = False)
x_train_fever_bp = ohe.fit_transform(x_train[['Fever_Severity','Blood_Pressure']])
x_test_fever_bp = ohe.fit_transform(x_test[['Fever_Severity','Blood_Pressure']])
x_train_fever_bp

array([[0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       ...,
       [0., 1., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#extracting of age
x_train_age = x_train.drop(columns = ['Fever_Severity','Blood_Pressure','Gender']).values
x_test_age = x_test.drop(columns = ['Fever_Severity','Blood_Pressure','Gender']).values

In [ ]:
#joining all
x_train_transform = np.concatenate((x_train_age,x_train_fever_bp,x_train_gender), axis =1)
x_test_transform = np.concatenate((x_test_age,x_test_fever_bp,x_test_gender), axis =1)
x_train_transform

array([[70.,  0.,  0.,  0.,  0.,  0.],
       [83.,  0.,  0.,  0.,  1.,  1.],
       [11.,  0.,  0.,  0.,  1.,  1.],
       ...,
       [82.,  0.,  1.,  0.,  1.,  1.],
       [ 2.,  1.,  0.,  0.,  0.,  0.],
       [46.,  0.,  0.,  0.,  0.,  1.]])

With column transformer

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', OneHotEncoder(sparse_output = False, drop = 'first'), ['Fever_Severity','Blood_Pressure']),
    ('tnf2',OrdinalEncoder(categories=[['Male','Female']]),['Gender'])
],remainder='passthrough')

In [ ]:
transformer.fit_transform(x_train)

array([[ 0.,  0.,  0.,  0.,  0., 70.],
       [ 0.,  0.,  0.,  1.,  1., 83.],
       [ 0.,  0.,  0.,  1.,  1., 11.],
       ...,
       [ 0.,  1.,  0.,  1.,  1., 82.],
       [ 1.,  0.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  0.,  0.,  1., 46.]])

In [ ]:
transformer.transform(x_test)

array([[ 0.,  0.,  0.,  0.,  1., 17.],
       [ 1.,  0.,  0.,  0.,  0., 90.],
       [ 0.,  0.,  1.,  0.,  0., 64.],
       ...,
       [ 0.,  0.,  0.,  0.,  0., 20.],
       [ 1.,  0.,  1.,  0.,  1., 22.],
       [ 0.,  1.,  0.,  1.,  0., 60.]])