<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/n_u_m_p_y7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
# Creating NP arrays

In [76]:
import numpy as np      # --> 2D,3D, dtype, np.arange,

In [77]:
# 1D, 2D, 3D
a = np.array([1,2,3])
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b)
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [78]:
# dtype = Pasandita datatype conversion
a = np.array([1,2,3], dtype = str)   # complex, float, bool etc
print(a)

['1' '2' '3']


In [79]:
# np.arange
a = np.arange(1,11,2)
print(a)

[1 3 5 7 9]


In [80]:
# with range --> reshape is often used
a = np.arange(1,21,2).reshape(2,5)   # total number of items in array should be equal to the reshape's product
print(a)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [81]:
# np.one/zeros/random
print(np.ones((3,3)))    # can be used for intialise values
print(np.zeros((4,4)))
print(np.random.random((3,4)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.67624326 0.81987098 0.20023444 0.68964487]
 [0.28613837 0.97896543 0.37741143 0.15130844]
 [0.68436128 0.08170687 0.02013948 0.28144623]]


In [82]:
# np.linspace  -->   in a given range at equal distance generate points
print(np.linspace(-10,10,20))

[-10.          -8.94736842  -7.89473684  -6.84210526  -5.78947368
  -4.73684211  -3.68421053  -2.63157895  -1.57894737  -0.52631579
   0.52631579   1.57894737   2.63157895   3.68421053   4.73684211
   5.78947368   6.84210526   7.89473684   8.94736842  10.        ]


In [83]:
# np.identity  --> can create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
# Array Attributes

In [85]:
a1 = np.arange(10)
a2 = np.arange(10, dtype = float).reshape(5,2)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [86]:
# ndim --> tells dimension
a2.ndim

2

In [87]:
# shape --> tells shape
a1.shape

(10,)

In [88]:
# size
a1.size

10

In [89]:
# item size --> bytes output
a1.itemsize

8

In [90]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [91]:
# Changing datatype
# astype
a3.astype("int32")

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [92]:
# Array operation

In [93]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [94]:
# Scalar operations
# Arithmetic
a1 * 2  # +,-,%,//,/,** etc

# relational
a2 > 25 # <,>=,<=,==,!= etc

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [95]:
# Vector operation  --> when applied between np arrays
# Arithmetic
a1 * a2 # **,/,//,+ etc depending upon the arrays

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [96]:
# Numpy function

In [97]:
a1 = np.round(np.random.random((3,3)) *100)
a1

array([[ 8., 83., 35.],
       [22., 70., 20.],
       [82., 38., 32.]])

In [98]:
# max/min/sum/prod
np.max(a1,axis = 1)
np.min(a1)
np.sum(a1)
np.prod(a1)

np.float64(71373051904000.0)

In [99]:
# mean/median/std/var
np.mean(a1, axis = 0)
np.median(a1)
np.std(a1)
np.var(a1)

np.float64(694.8888888888889)

In [100]:
# trigonometric function
np.sin(a1)
np.cos(a1)
# and few more

array([[-0.14550003,  0.24954012, -0.90369221],
       [-0.99996083,  0.6333192 ,  0.40808206],
       [ 0.9496777 ,  0.95507364,  0.83422336]])

In [101]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [102]:
# log and exponents
np.log(a1)
np.exp(a1)

array([[2.98095799e+03, 1.11286375e+36, 1.58601345e+15],
       [3.58491285e+09, 2.51543867e+30, 4.85165195e+08],
       [4.09399696e+35, 3.18559318e+16, 7.89629602e+13]])

In [103]:
# round/floor/ceil
a4 = np.random.random((2,2))*100
a5 = np.round(a4)
a6 = np.floor(a4)
a7 = np.ceil(a4)

In [104]:
# indexing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [105]:
a1[0:10:2]

array([0, 2, 4, 6, 8])

In [106]:
a2[1,2]  # (row,columns)   # 2D
a2[1,3]

np.int64(7)

In [107]:
a3[1,0,1]            # (which 2d array, row, column)             # 3D matrix/tensor   # 4D provide 4 values
a3[0,0,0]

np.int64(0)

In [108]:
# Slicing
a1[2:10:2]   # start:end:step

array([2, 4, 6, 8])

In [109]:
a2[0,:]  # for row -> [which row: how many column]            # 2D
a2[:,1]  # for column -> [how mnay row: which column]            # 2D
a2[1:3,1:3]  # specific
a2[::2,::3]  # with steps
a2[::2,1::2]   # row : column
a2[1,::3]
a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [111]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [116]:
a3[1,:,1:3:2]   # which 2d array:row:column
a3[2,1:3,1:3]
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [118]:
# Iterating
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [121]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [122]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [123]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [132]:
# transpose
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [134]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [135]:
# ravel
a3.ravel()  # converts to 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [140]:
# Stacking
# horizontal stacking
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
np.hstack((a1,a2,))
# vertical stack
np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])