<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/n_u_m_p_y2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Creating NP arrays

In [ ]:
import numpy as np      # --> 2D,3D, dtype, np.arange,

In [ ]:
# 1D, 2D, 3D
a = np.array([1,2,3])
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b)
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
# dtype = Pasandita datatype conversion
a = np.array([1,2,3], dtype = str)   # complex, float, bool etc
print(a)

['1' '2' '3']


In [ ]:
# np.arange
a = np.arange(1,11,2)
print(a)

[1 3 5 7 9]


In [ ]:
# with range --> reshape is often used
a = np.arange(1,21,2).reshape(2,5)   # total number of items in array should be equal to the reshape's product
print(a)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [ ]:
# np.one/zeros/random
print(np.ones((3,3)))    # can be used for intialise values
print(np.zeros((4,4)))
print(np.random.random((3,4)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.53456416 0.1490804  0.64987465 0.5757104 ]
 [0.64998907 0.33545647 0.34762888 0.32379973]
 [0.40706734 0.51845151 0.75132391 0.3037843 ]]


In [ ]:
# np.linspace  -->   in a given range at equal distance generate points
print(np.linspace(-10,10,20))

[-10.          -8.94736842  -7.89473684  -6.84210526  -5.78947368
  -4.73684211  -3.68421053  -2.63157895  -1.57894737  -0.52631579
   0.52631579   1.57894737   2.63157895   3.68421053   4.73684211
   5.78947368   6.84210526   7.89473684   8.94736842  10.        ]


In [ ]:
# np.identity  --> can create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Array Attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(10, dtype = float).reshape(5,2)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# ndim --> tells dimension
a2.ndim

2

In [ ]:
# shape --> tells shape
a1.shape

(10,)

In [ ]:
# size
a1.size

10

In [ ]:
# item size --> bytes output
a1.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [ ]:
# Changing datatype
# astype
a3.astype("int32")

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
# Array operation

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# Scalar operations
# Arithmetic
a1 * 2  # +,-,%,//,/,** etc

# relational
a2 > 25 # <,>=,<=,==,!= etc

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# Vector operation  --> when applied between np arrays
# Arithmetic
a1 * a2 # **,/,//,+ etc depending upon the arrays

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])