<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/n_u_m_p_y5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# Creating NP arrays

In [22]:
import numpy as np      # --> 2D,3D, dtype, np.arange,

In [23]:
# 1D, 2D, 3D
a = np.array([1,2,3])
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b)
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [24]:
# dtype = Pasandita datatype conversion
a = np.array([1,2,3], dtype = str)   # complex, float, bool etc
print(a)

['1' '2' '3']


In [25]:
# np.arange
a = np.arange(1,11,2)
print(a)

[1 3 5 7 9]


In [26]:
# with range --> reshape is often used
a = np.arange(1,21,2).reshape(2,5)   # total number of items in array should be equal to the reshape's product
print(a)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [27]:
# np.one/zeros/random
print(np.ones((3,3)))    # can be used for intialise values
print(np.zeros((4,4)))
print(np.random.random((3,4)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.37386189 0.71212763 0.25295344 0.62651144]
 [0.47099793 0.99274656 0.49302844 0.33247019]
 [0.5463006  0.15823105 0.78085613 0.6941355 ]]


In [28]:
# np.linspace  -->   in a given range at equal distance generate points
print(np.linspace(-10,10,20))

[-10.          -8.94736842  -7.89473684  -6.84210526  -5.78947368
  -4.73684211  -3.68421053  -2.63157895  -1.57894737  -0.52631579
   0.52631579   1.57894737   2.63157895   3.68421053   4.73684211
   5.78947368   6.84210526   7.89473684   8.94736842  10.        ]


In [29]:
# np.identity  --> can create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Array Attributes

In [31]:
a1 = np.arange(10)
a2 = np.arange(10, dtype = float).reshape(5,2)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [32]:
# ndim --> tells dimension
a2.ndim

2

In [33]:
# shape --> tells shape
a1.shape

(10,)

In [34]:
# size
a1.size

10

In [35]:
# item size --> bytes output
a1.itemsize

8

In [36]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [37]:
# Changing datatype
# astype
a3.astype("int32")

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [38]:
# Array operation

In [39]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [40]:
# Scalar operations
# Arithmetic
a1 * 2  # +,-,%,//,/,** etc

# relational
a2 > 25 # <,>=,<=,==,!= etc

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [41]:
# Vector operation  --> when applied between np arrays
# Arithmetic
a1 * a2 # **,/,//,+ etc depending upon the arrays

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [42]:
# Numpy function

In [43]:
a1 = np.round(np.random.random((3,3)) *100)
a1

array([[77., 58., 61.],
       [95., 18., 35.],
       [26., 60., 84.]])

In [44]:
# max/min/sum/prod
np.max(a1,axis = 1)
np.min(a1)
np.sum(a1)
np.prod(a1)

np.float64(2136567376944000.0)

In [45]:
# mean/median/std/var
np.mean(a1, axis = 0)
np.median(a1)
np.std(a1)
np.var(a1)

np.float64(618.320987654321)

In [46]:
# trigonometric function
np.sin(a1)
np.cos(a1)
# and few more

array([[-0.03097503,  0.11918014, -0.25810164],
       [ 0.73017356,  0.66031671, -0.90369221],
       [ 0.64691932, -0.95241298, -0.6800235 ]])

In [47]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [48]:
# log and exponents
np.log(a1)
np.exp(a1)

array([[2.75851345e+33, 1.54553894e+25, 3.10429794e+26],
       [1.81123908e+41, 6.56599691e+07, 1.58601345e+15],
       [1.95729609e+11, 1.14200739e+26, 3.02507732e+36]])

In [49]:
# round/floor/ceil
a4 = np.random.random((2,2))*100
a5 = np.round(a4)
a6 = np.floor(a4)
a7 = np.ceil(a4)

In [51]:
# indexing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [52]:
a1[0:10:2]

array([0, 2, 4, 6, 8])

In [58]:
a2[1,2]  # (row,columns)   # 2D
a2[1,3]

np.int64(7)

In [61]:
a3[1,0,1]            # (which 2d array, row, column)             # 3D matrix/tensor   # 4D provide 4 values
a3[0,0,0]

np.int64(0)