<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/n_u_m_p_y4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
# Creating NP arrays

In [55]:
import numpy as np      # --> 2D,3D, dtype, np.arange,

In [56]:
# 1D, 2D, 3D
a = np.array([1,2,3])
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b)
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [57]:
# dtype = Pasandita datatype conversion
a = np.array([1,2,3], dtype = str)   # complex, float, bool etc
print(a)

['1' '2' '3']


In [58]:
# np.arange
a = np.arange(1,11,2)
print(a)

[1 3 5 7 9]


In [59]:
# with range --> reshape is often used
a = np.arange(1,21,2).reshape(2,5)   # total number of items in array should be equal to the reshape's product
print(a)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [60]:
# np.one/zeros/random
print(np.ones((3,3)))    # can be used for intialise values
print(np.zeros((4,4)))
print(np.random.random((3,4)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.39445982 0.27767718 0.54320282 0.21513508]
 [0.68357395 0.5439952  0.29266062 0.59090091]
 [0.07708619 0.14923699 0.97008348 0.95513701]]


In [61]:
# np.linspace  -->   in a given range at equal distance generate points
print(np.linspace(-10,10,20))

[-10.          -8.94736842  -7.89473684  -6.84210526  -5.78947368
  -4.73684211  -3.68421053  -2.63157895  -1.57894737  -0.52631579
   0.52631579   1.57894737   2.63157895   3.68421053   4.73684211
   5.78947368   6.84210526   7.89473684   8.94736842  10.        ]


In [62]:
# np.identity  --> can create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
# Array Attributes

In [64]:
a1 = np.arange(10)
a2 = np.arange(10, dtype = float).reshape(5,2)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [65]:
# ndim --> tells dimension
a2.ndim

2

In [66]:
# shape --> tells shape
a1.shape

(10,)

In [67]:
# size
a1.size

10

In [68]:
# item size --> bytes output
a1.itemsize

8

In [69]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [70]:
# Changing datatype
# astype
a3.astype("int32")

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [71]:
# Array operation

In [72]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [73]:
# Scalar operations
# Arithmetic
a1 * 2  # +,-,%,//,/,** etc

# relational
a2 > 25 # <,>=,<=,==,!= etc

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [74]:
# Vector operation  --> when applied between np arrays
# Arithmetic
a1 * a2 # **,/,//,+ etc depending upon the arrays

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [75]:
# Numpy function

In [87]:
a1 = np.round(np.random.random((3,3)) *100)
a1

array([[ 1., 64., 55.],
       [61., 54.,  4.],
       [ 4., 26., 31.]])

In [88]:
# max/min/sum/prod
np.max(a1,axis = 1)
np.min(a1)
np.sum(a1)
np.prod(a1)

np.float64(149527572480.0)

In [89]:
# mean/median/std/var
np.mean(a1, axis = 0)
np.median(a1)
np.std(a1)
np.var(a1)

np.float64(603.1111111111111)

In [90]:
# trigonometric function
np.sin(a1)
np.cos(a1)
# and few more

array([[ 0.54030231,  0.39185723,  0.02212676],
       [-0.25810164, -0.82930983, -0.65364362],
       [-0.65364362,  0.64691932,  0.91474236]])

In [91]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [92]:
# log and exponents
np.log(a1)
np.exp(a1)

array([[2.71828183e+00, 6.23514908e+27, 7.69478527e+23],
       [3.10429794e+26, 2.83075330e+23, 5.45981500e+01],
       [5.45981500e+01, 1.95729609e+11, 2.90488497e+13]])

In [105]:
# round/floor/ceil
a4 = np.random.random((2,2))*100
a5 = np.round(a4)
a6 = np.floor(a4)
a7 = np.ceil(a4)